GOOGLE_API_KEY = "your-google-api-key"
TO_EMAIL = "your-target-email@example.com"
FROM_EMAIL = "your-gmail@gmail.com"

CLIENT_SECRET_JSON = """
{
    "installed": {
        client_id= "573959129688-g8rsclts9c0d1c7pl562k0o3l1c93sku.apps.googleusercontent.com"
        project_id= "sunny-strategy-459403-k7"
        auth_uri= "https://accounts.google.com/o/oauth2/auth"
        token_uri= "https://oauth2.googleapis.com/token"
        auth_provider_x509_cert_url= "https://www.googleapis.com/oauth2/v1/certs"
        client_secret= "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"
    }
}
"""