GOOGLE_API_KEY = "AIzaSyARHCCFSs3ZXnZnwpGFfSct22xLPHHsa7k"
TO_EMAIL= "saimaniritish1942@gmail.com"
FROM_EMAIL = "saimaniritish1942@gmail.com"

CLIENT_SECRET_JSON = """
{
    "web": {
        client_id= "825430285214-ppdek19bijbckrmlu93hp7mtsa7g5fdh.apps.googleusercontent.com"
        project_id= "gen-lang-client-0679695537"
        auth_uri= "https://accounts.google.com/o/oauth2/auth"
        token_uri= "https://oauth2.googleapis.com/token"
        auth_provider_x509_cert_url= "https://www.googleapis.com/oauth2/v1/certs"
        client_secret= "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"
        redirect_uri = "https://codingcoach-knmyouv8hzeqbhkstsrwz2.streamlit.app/oauth2callback
    }
}
"""